import { VocabWord, CEFRLevel } from "@/types";

export interface BankWord extends VocabWord {
  level: CEFRLevel;
  topic: string;
}

export const VOCAB_BANK: BankWord[] = [
  // ── A1 – Everyday Basics ──────────────────────────────────────────────────
  { id: "b1",   level:"A1", topic:"Greetings",   word:"Good morning",    translation:"בוקר טוב",          example:"Good morning! How are you?" },
  { id: "b2",   level:"A1", topic:"Greetings",   word:"Good night",      translation:"לילה טוב",           example:"Good night! Sleep well." },
  { id: "b3",   level:"A1", topic:"Greetings",   word:"Nice to meet you",translation:"נעים להכיר",         example:"Nice to meet you, David!" },
  { id: "b4",   level:"A1", topic:"Greetings",   word:"How are you?",    translation:"מה שלומך?",          example:"Hi! How are you today?" },
  { id: "b5",   level:"A1", topic:"Greetings",   word:"Fine, thanks",    translation:"בסדר, תודה",         example:"Fine, thanks. And you?" },
  { id: "b6",   level:"A1", topic:"Numbers",     word:"Hundred / Thousand",translation:"מאה / אלף",       example:"There are a thousand students here." },
  { id: "b7",   level:"A1", topic:"Numbers",     word:"First / Last",    translation:"ראשון / אחרון",      example:"I am the first in the queue." },
  { id: "b8",   level:"A1", topic:"Places",      word:"School / University",translation:"בית ספר / אוניברסיטה",example:"She studies at a university." },
  { id: "b9",   level:"A1", topic:"Places",      word:"Hospital / Bank / Post office",translation:"בית חולים / בנק / דואר",example:"I need to go to the bank." },
  { id: "b10",  level:"A1", topic:"Places",      word:"Park / Beach / Mountain",translation:"פארק / חוף / הר",example:"We walk in the park every Sunday." },
  { id: "b11",  level:"A1", topic:"Home",        word:"Bedroom / Bathroom",translation:"חדר שינה / חדר אמבטיה",example:"My bedroom is upstairs." },
  { id: "b12",  level:"A1", topic:"Home",        word:"TV / Computer / Phone",translation:"טלוויזיה / מחשב / טלפון",example:"I watch TV in the evening." },
  { id: "b13",  level:"A1", topic:"Food",        word:"Apple / Banana / Orange",translation:"תפוח / בננה / תפוז",example:"I eat an apple every day." },
  { id: "b14",  level:"A1", topic:"Food",        word:"Water / Milk / Juice",translation:"מים / חלב / מיץ",example:"Can I have a glass of water?" },
  { id: "b15",  level:"A1", topic:"Food",        word:"Breakfast / Lunch / Dinner",translation:"ארוחת בוקר / צהריים / ערב",example:"We have dinner at 7." },
  { id: "b16",  level:"A1", topic:"Clothes",     word:"Shirt / Trousers / Shoes",translation:"חולצה / מכנסיים / נעליים",example:"I wear a white shirt to work." },
  { id: "b17",  level:"A1", topic:"Clothes",     word:"Dress / Jacket / Hat",translation:"שמלה / ז'קט / כובע",example:"She wears a red dress." },
  { id: "b18",  level:"A1", topic:"Transport",   word:"Car / Bus / Train / Plane",translation:"מכונית / אוטובוס / רכבת / מטוס",example:"I take the bus to work." },
  { id: "b19",  level:"A1", topic:"Emotions",    word:"Happy / Sad / Angry",translation:"שמח / עצוב / כועס",example:"She is very happy today." },
  { id: "b20",  level:"A1", topic:"Emotions",    word:"Tired / Bored / Excited",translation:"עייף / משועמם / נרגש",example:"I'm so tired – I need to sleep." },
  { id: "b21",  level:"A1", topic:"Actions",     word:"Eat / Drink / Sleep",translation:"לאכול / לשתות / לישון",example:"I sleep eight hours every night." },
  { id: "b22",  level:"A1", topic:"Actions",     word:"Walk / Run / Jump",translation:"ללכת / לרוץ / לקפוץ",example:"She runs every morning." },
  { id: "b23",  level:"A1", topic:"Actions",     word:"Read / Write / Listen",translation:"לקרוא / לכתוב / להקשיב",example:"Please listen carefully." },
  { id: "b24",  level:"A1", topic:"Actions",     word:"Open / Close / Turn on / Turn off",translation:"לפתוח / לסגור / להדליק / לכבות",example:"Please close the window." },
  { id: "b25",  level:"A1", topic:"Descriptions",word:"New / Old / Clean / Dirty",translation:"חדש / ישן / נקי / מלוכלך",example:"I need a clean shirt." },
  { id: "b26",  level:"A1", topic:"Descriptions",word:"Long / Short / Tall / Small",translation:"ארוך / קצר / גבוה / קטן",example:"She has long dark hair." },
  { id: "b27",  level:"A1", topic:"Descriptions",word:"Fast / Slow / Loud / Quiet",translation:"מהיר / איטי / רועש / שקט",example:"Please be quiet – the baby is sleeping." },
  { id: "b28",  level:"A1", topic:"Questions",   word:"What / Where / When / Why / Who",translation:"מה / איפה / מתי / למה / מי",example:"Where do you live?" },
  { id: "b29",  level:"A1", topic:"Questions",   word:"How much / How many / How long",translation:"כמה (מחיר) / כמה (כמות) / כמה זמן",example:"How long does it take?" },
  { id: "b30",  level:"A1", topic:"Basics",      word:"And / But / Or / Because",translation:"ו / אבל / או / כי",example:"I like tea but I don't like coffee." },

  // ── A2 – Building Blocks ──────────────────────────────────────────────────
  { id: "b50",  level:"A2", topic:"Travel",      word:"Passport / Visa / Customs",translation:"דרכון / ויזה / מכס",example:"Don't forget your passport!" },
  { id: "b51",  level:"A2", topic:"Travel",      word:"Hotel / Hostel / Apartment",translation:"מלון / הוסטל / דירה",example:"We booked a hotel near the beach." },
  { id: "b52",  level:"A2", topic:"Travel",      word:"Ticket / Seat / Baggage",translation:"כרטיס / מושב / מטען",example:"My baggage was lost at the airport." },
  { id: "b53",  level:"A2", topic:"Shopping",    word:"Size / Colour / Style",translation:"מידה / צבע / סגנון",example:"Do you have this in a smaller size?" },
  { id: "b54",  level:"A2", topic:"Shopping",    word:"Try on / Fit / Suit",translation:"לנסות / להתאים / להתאים",example:"Can I try this on, please?" },
  { id: "b55",  level:"A2", topic:"Shopping",    word:"Bargain / Refund / Exchange",translation:"מציאה / החזר / החלפה",example:"Can I get a refund for this?" },
  { id: "b56",  level:"A2", topic:"Daily life",  word:"Alarm clock / Shower / Brush teeth",translation:"שעון מעורר / מקלחת / לצחצח שיניים",example:"I set my alarm for 6:30." },
  { id: "b57",  level:"A2", topic:"Daily life",  word:"Commute / Traffic / Rush hour",translation:"נסיעה לעבודה / פקקים / שעת שיא",example:"The rush hour traffic is terrible." },
  { id: "b58",  level:"A2", topic:"Health",      word:"Exercise / Diet / Sleep",translation:"פעילות / דיאטה / שינה",example:"A good diet and sleep are important." },
  { id: "b59",  level:"A2", topic:"Health",      word:"Dentist / Injection / Prescription",translation:"רופא שיניים / זריקה / מרשם",example:"I have an appointment with the dentist." },
  { id: "b60",  level:"A2", topic:"Emotions",    word:"Nervous / Confident / Surprised",translation:"עצבני / בטוח בעצמו / מופתע",example:"I was nervous before the interview." },
  { id: "b61",  level:"A2", topic:"Emotions",    word:"Lonely / Comfortable / Grateful",translation:"בודד / נוח / אסיר תודה",example:"I'm so grateful for your help." },
  { id: "b62",  level:"A2", topic:"Education",   word:"Homework / Exam / Grade",translation:"שיעורי בית / מבחן / ציון",example:"I passed all my exams this year." },
  { id: "b63",  level:"A2", topic:"Education",   word:"Lesson / Subject / Timetable",translation:"שיעור / מקצוע / לוח זמנים",example:"My favourite subject is maths." },
  { id: "b64",  level:"A2", topic:"Nature",      word:"River / Sea / Forest / Desert",translation:"נהר / ים / יער / מדבר",example:"The Dead Sea is the lowest point on Earth." },
  { id: "b65",  level:"A2", topic:"Nature",      word:"Animal / Plant / Flower",translation:"בעל חיים / צמח / פרח",example:"I love the smell of flowers." },
  { id: "b66",  level:"A2", topic:"Tech",        word:"Internet / Email / Password",translation:"אינטרנט / דואל / סיסמה",example:"Don't share your password with anyone." },
  { id: "b67",  level:"A2", topic:"Tech",        word:"Smartphone / Camera / Headphones",translation:"סמארטפון / מצלמה / אוזניות",example:"I listen to podcasts with my headphones." },
  { id: "b68",  level:"A2", topic:"Food",        word:"Spicy / Salty / Sweet / Sour",translation:"חריף / מלוח / מתוק / חמוץ",example:"This sauce is very spicy." },
  { id: "b69",  level:"A2", topic:"Food",        word:"Menu / Order / Tip",translation:"תפריט / להזמין / טיפ",example:"I always leave a tip for good service." },
  { id: "b70",  level:"A2", topic:"Phrases",     word:"I'm afraid not / I'm not sure",translation:"חוששני שלא / אני לא בטוח",example:"I'm afraid we don't have any left." },
  { id: "b71",  level:"A2", topic:"Phrases",     word:"Could you help me?",translation:"האם תוכל לעזור לי?",example:"Excuse me, could you help me find this street?" },
  { id: "b72",  level:"A2", topic:"Phrases",     word:"Let me know / Get back to you",translation:"תעדכן אותי / אחזור אליך",example:"Let me know when you arrive." },
  { id: "b73",  level:"A2", topic:"Work",        word:"Boss / Colleague / Employee",translation:"בוס / עמית / עובד",example:"My colleagues are very supportive." },
  { id: "b74",  level:"A2", topic:"Work",        word:"Office / Meeting / Deadline",translation:"משרד / פגישה / דדליין",example:"We have a team meeting every Monday." },
  { id: "b75",  level:"A2", topic:"Work",        word:"Busy / Productive / Organised",translation:"עסוק / פרודוקטיבי / מאורגן",example:"I try to stay organised at work." },
  { id: "b76",  level:"A2", topic:"Leisure",     word:"Cinema / Concert / Museum",translation:"קולנוע / קונצרט / מוזיאון",example:"Let's go to the cinema tonight." },
  { id: "b77",  level:"A2", topic:"Leisure",     word:"Play sports / Go for a walk",translation:"לשחק ספורט / ללכת לטיול",example:"I go for a walk every morning." },
  { id: "b78",  level:"A2", topic:"Describing",  word:"Interesting / Boring / Funny / Serious",translation:"מעניין / משעמם / מצחיק / רציני",example:"The lecture was really interesting." },
  { id: "b79",  level:"A2", topic:"Describing",  word:"Crowded / Empty / Noisy / Peaceful",translation:"עמוס / ריק / רועש / שלוו",example:"The beach was crowded in summer." },
  { id: "b80",  level:"A2", topic:"Connecting",  word:"First of all / Then / Finally",translation:"קודם כל / אחר כך / לבסוף",example:"First of all, let me introduce myself." },

  // ── B1 – Intermediate ─────────────────────────────────────────────────────
  { id: "b100", level:"B1", topic:"Work",        word:"Negotiate / Promote / Resign",translation:"לנהל משא ומתן / לקדם / להתפטר",example:"She resigned after 10 years." },
  { id: "b101", level:"B1", topic:"Work",        word:"Freelancer / Entrepreneur / Start-up",translation:"פרילנסר / יזם / סטארטאפ",example:"He left his job to start his own business." },
  { id: "b102", level:"B1", topic:"Society",     word:"Volunteer / Charity / Donation",translation:"מתנדב / צדקה / תרומה",example:"She volunteers at a local food bank." },
  { id: "b103", level:"B1", topic:"Society",     word:"Protest / Campaign / Petition",translation:"מחאה / קמפיין / עצומה",example:"They organised a petition with 10,000 signatures." },
  { id: "b104", level:"B1", topic:"Media",       word:"Headline / Article / Journalist",translation:"כותרת / מאמר / עיתונאי",example:"Did you read the headline today?" },
  { id: "b105", level:"B1", topic:"Media",       word:"Opinion / Debate / Argument",translation:"דעה / ויכוח / טיעון",example:"We had an interesting debate about social media." },
  { id: "b106", level:"B1", topic:"Environment", word:"Climate / Carbon / Emission",translation:"אקלים / פחמן / פליטה",example:"Carbon emissions must be reduced urgently." },
  { id: "b107", level:"B1", topic:"Environment", word:"Plastic / Pollution / Waste",translation:"פלסטיק / זיהום / פסולת",example:"We need to reduce plastic waste." },
  { id: "b108", level:"B1", topic:"Health",      word:"Mental health / Anxiety / Therapy",translation:"בריאות נפשית / חרדה / טיפול",example:"Therapy helped me manage my anxiety." },
  { id: "b109", level:"B1", topic:"Health",      word:"Symptoms / Diagnose / Treatment",translation:"תסמינים / לאבחן / טיפול",example:"The doctor diagnosed a vitamin deficiency." },
  { id: "b110", level:"B1", topic:"Travel",      word:"Explore / Discover / Adventure",translation:"לחקור / לגלות / הרפתקה",example:"We explored the old city on foot." },
  { id: "b111", level:"B1", topic:"Travel",      word:"Culture shock / Local customs / Etiquette",translation:"הלם תרבות / מנהגים מקומיים / נימוסים",example:"I experienced culture shock when I moved abroad." },
  { id: "b112", level:"B1", topic:"Relationships",word:"Trust / Respect / Support",translation:"אמון / כבוד / תמיכה",example:"A strong relationship is built on trust." },
  { id: "b113", level:"B1", topic:"Relationships",word:"Argument / Apologise / Forgive",translation:"ריב / להתנצל / לסלוח",example:"He apologised and she forgave him." },
  { id: "b114", level:"B1", topic:"Personal",    word:"Ambitious / Determined / Passionate",translation:"שאפתן / נחוש / נלהב",example:"She is passionate about environmental issues." },
  { id: "b115", level:"B1", topic:"Personal",    word:"Improve / Achieve / Overcome",translation:"לשפר / להשיג / להתגבר",example:"She overcame many obstacles to get her degree." },
  { id: "b116", level:"B1", topic:"Language",    word:"Fluent / Accent / Phrase",translation:"שוטף / מבטא / ביטוי",example:"She speaks French fluently." },
  { id: "b117", level:"B1", topic:"Language",    word:"Misunderstand / Context / Gesture",translation:"להבין לא נכון / הקשר / תנועה",example:"I misunderstood his gesture." },
  { id: "b118", level:"B1", topic:"Technology",  word:"Update / Download / Install",translation:"לעדכן / להוריד / להתקין",example:"Please update the software before the meeting." },
  { id: "b119", level:"B1", topic:"Technology",  word:"Screen / Battery / Charger",translation:"מסך / סוללה / מטען",example:"My phone battery is almost dead." },
  { id: "b120", level:"B1", topic:"Food",        word:"Ingredient / Recipe / Taste",translation:"מרכיב / מתכון / טעם",example:"The secret ingredient is cardamom." },
  { id: "b121", level:"B1", topic:"Opinions",    word:"In my view / I'd argue / Personally",translation:"לדעתי / אני טוען / אישית",example:"In my view, public transport is essential." },
  { id: "b122", level:"B1", topic:"Opinions",    word:"Advantage / Disadvantage / Trade-off",translation:"יתרון / חיסרון / פשרה",example:"Every advantage has a trade-off." },
  { id: "b123", level:"B1", topic:"Feelings",    word:"Regret / Disappoint / Inspire",translation:"לצטער / לאכזב / לעורר השראה",example:"I regret not travelling more when I was young." },
  { id: "b124", level:"B1", topic:"Feelings",    word:"Jealous / Curious / Optimistic",translation:"קנאי / סקרן / אופטימי",example:"Stay curious – never stop learning." },
  { id: "b125", level:"B1", topic:"Connecting",  word:"As a result / Therefore / Consequently",translation:"כתוצאה מכך / לכן / כתוצאה",example:"He studied hard; as a result, he passed." },
  { id: "b126", level:"B1", topic:"Connecting",  word:"In addition / Furthermore / Moreover",translation:"בנוסף / יתר על כן / יתרה מזאת",example:"Furthermore, the cost was much lower." },
  { id: "b127", level:"B1", topic:"Describing",  word:"Remarkable / Significant / Inevitable",translation:"מרשים / משמעותי / בלתי נמנע",example:"It was inevitable that they would disagree." },
  { id: "b128", level:"B1", topic:"Describing",  word:"Complicated / Straightforward / Vague",translation:"מסובך / פשוט / מעורפל",example:"The instructions are too vague to follow." },
  { id: "b129", level:"B1", topic:"Money",       word:"Budget / Invest / Debt",translation:"תקציב / להשקיע / חוב",example:"I'm trying to pay off my student debt." },

  // ── B2 – Upper Intermediate ───────────────────────────────────────────────
  { id: "b150", level:"B2", topic:"Critical thinking",word:"Assumption / Bias / Perspective",translation:"הנחה / הטיה / נקודת מבט",example:"We all have unconscious biases." },
  { id: "b151", level:"B2", topic:"Critical thinking",word:"Evidence / Counter-argument / Fallacy",translation:"ראיה / טיעון נגד / כשל לוגי",example:"Your argument contains a logical fallacy." },
  { id: "b152", level:"B2", topic:"Economy",     word:"Inflation / Recession / GDP",translation:"אינפלציה / מיתון / תמ\"ג",example:"High inflation reduces purchasing power." },
  { id: "b153", level:"B2", topic:"Economy",     word:"Subsidy / Tax / Welfare",translation:"סובסידיה / מס / רווחה",example:"Subsidies help struggling industries." },
  { id: "b154", level:"B2", topic:"Politics",    word:"Democracy / Election / Parliament",translation:"דמוקרטיה / בחירות / פרלמנט",example:"Elections are held every four years." },
  { id: "b155", level:"B2", topic:"Politics",    word:"Policy / Reform / Legislation",translation:"מדיניות / רפורמה / חקיקה",example:"The government introduced new education legislation." },
  { id: "b156", level:"B2", topic:"Science",     word:"Theory / Hypothesis / Experiment",translation:"תיאוריה / היפותזה / ניסוי",example:"The experiment confirmed the hypothesis." },
  { id: "b157", level:"B2", topic:"Science",     word:"Data / Analysis / Conclusion",translation:"נתונים / ניתוח / מסקנה",example:"The data analysis took three months." },
  { id: "b158", level:"B2", topic:"Culture",     word:"Tradition / Heritage / Identity",translation:"מסורת / מורשת / זהות",example:"Our heritage defines our identity." },
  { id: "b159", level:"B2", topic:"Culture",     word:"Influence / Reflect / Evolve",translation:"להשפיע / לשקף / להתפתח",example:"Language reflects cultural values." },
  { id: "b160", level:"B2", topic:"Psychology",  word:"Motivation / Behaviour / Perception",translation:"מוטיבציה / התנהגות / תפיסה",example:"Motivation is key to learning." },
  { id: "b161", level:"B2", topic:"Psychology",  word:"Cognitive / Emotional / Rational",translation:"קוגניטיבי / רגשי / רציונלי",example:"Cognitive biases affect decision-making." },
  { id: "b162", level:"B2", topic:"Formal English",word:"Regarding / With respect to / Pertaining to",translation:"בנוגע ל- / ביחס ל- / הנוגע ל-",example:"Regarding your request, we are happy to help." },
  { id: "b163", level:"B2", topic:"Formal English",word:"Nevertheless / Notwithstanding / Albeit",translation:"בכל זאת / על אף / אם כי",example:"The project was difficult, albeit rewarding." },
  { id: "b164", level:"B2", topic:"Formal English",word:"Henceforth / Thereby / Whereby",translation:"מעתה / בכך / לפיו",example:"Henceforth, all meetings will be recorded." },
  { id: "b165", level:"B2", topic:"Idioms",      word:"A blessing in disguise / Silver lining",translation:"ברכה במסווה / צד חיובי",example:"Losing that job was a blessing in disguise." },
  { id: "b166", level:"B2", topic:"Idioms",      word:"Hit the nail on the head / Miss the point",translation:"לפגוע בול / לפספס את הנקודה",example:"You hit the nail on the head with that idea." },
  { id: "b167", level:"B2", topic:"Idioms",      word:"On the fence / Take a stand",translation:"גדר אמצעית / לנקוט עמדה",example:"You can't stay on the fence on this issue." },
  { id: "b168", level:"B2", topic:"Narrative",   word:"Dramatically / Unexpectedly / Significantly",translation:"דרמטית / באופן בלתי צפוי / בצורה משמעותית",example:"The situation changed dramatically overnight." },
  { id: "b169", level:"B2", topic:"Narrative",   word:"Witness / Encounter / Reveal",translation:"להיות עד / להיתקל / לחשוף",example:"She encountered many difficulties abroad." },
  { id: "b170", level:"B2", topic:"Academic",    word:"Outline / Summarise / Evaluate",translation:"לסכם / לסכם / להעריך",example:"Please summarise the main arguments." },
  { id: "b171", level:"B2", topic:"Academic",    word:"Approach / Framework / Concept",translation:"גישה / מסגרת / מושג",example:"This framework helps analyse the problem." },
  { id: "b172", level:"B2", topic:"Technology",  word:"Blockchain / Cybersecurity / Encryption",translation:"בלוקצ'יין / אבטחת סייבר / הצפנה",example:"Strong encryption protects our data." },
  { id: "b173", level:"B2", topic:"Business",    word:"Pitch / Prototype / Scale",translation:"פרזנטציה / אב-טיפוס / להגדיל",example:"They pitched the idea to investors." },
  { id: "b174", level:"B2", topic:"Phrases",     word:"To put it another way / In other words",translation:"במילים אחרות",example:"To put it another way, the plan failed." },
  { id: "b175", level:"B2", topic:"Phrases",     word:"It goes without saying / Needless to say",translation:"מובן מאליו / אין צורך לומר",example:"Needless to say, we were all surprised." },
  { id: "b176", level:"B2", topic:"Describing",  word:"Subtle / Profound / Explicit",translation:"עדין / עמוק / מפורש",example:"The novel's humour is subtle but effective." },
  { id: "b177", level:"B2", topic:"Describing",  word:"Inevitable / Questionable / Debatable",translation:"בלתי נמנע / מפוקפק / שנוי במחלוקת",example:"His conclusion is highly questionable." },
  { id: "b178", level:"B2", topic:"Collocations",word:"Make a decision / Take action / Reach a conclusion",translation:"לקבל החלטה / לנקוט פעולה / להגיע למסקנה",example:"We need to take action immediately." },
  { id: "b179", level:"B2", topic:"Collocations",word:"Give a presentation / Raise awareness",translation:"להציג / להעלות מודעות",example:"She gave a brilliant presentation." },

  // ── C1 – Advanced ─────────────────────────────────────────────────────────
  { id: "b200", level:"C1", topic:"Academic",    word:"Epistemology / Ontology",translation:"תורת ידע / אונטולוגיה",example:"Epistemology asks: what can we know?" },
  { id: "b201", level:"C1", topic:"Academic",    word:"Discourse / Paradigm / Hegemony",translation:"שיח / פרדיגמה / הגמוניה",example:"The dominant paradigm is being challenged." },
  { id: "b202", level:"C1", topic:"Legal",       word:"Jurisdiction / Litigation / Precedent",translation:"סמכות שיפוט / ליטיגציה / תקדים",example:"This case sets a dangerous legal precedent." },
  { id: "b203", level:"C1", topic:"Legal",       word:"Liable / Comply / Infringe",translation:"אחראי / לציית / להפר",example:"The company failed to comply with the regulations." },
  { id: "b204", level:"C1", topic:"Medical",     word:"Pathology / Prognosis / Intervention",translation:"פתולוגיה / פרוגנוזה / התערבות",example:"Early intervention improves the prognosis significantly." },
  { id: "b205", level:"C1", topic:"Politics",    word:"Sovereignty / Referendum / Coalition",translation:"ריבונות / משאל עם / קואליציה",example:"The coalition collapsed after six months." },
  { id: "b206", level:"C1", topic:"Economics",   word:"Monetarist / Keynesian / Austerity",translation:"מוניטריסט / קיינסיאני / צנע",example:"Keynesian economists favour government spending." },
  { id: "b207", level:"C1", topic:"Literary",    word:"Allegory / Metaphor / Irony",translation:"אלגוריה / מטאפורה / אירוניה",example:"Animal Farm is an allegory for the Russian Revolution." },
  { id: "b208", level:"C1", topic:"Literary",    word:"Protagonist / Antagonist / Narrator",translation:"גיבור / אנטגוניסט / מספר",example:"The narrator is unreliable in this novel." },
  { id: "b209", level:"C1", topic:"Philosophy",  word:"Virtue / Autonomy / Justice",translation:"מידה טובה / אוטונומיה / צדק",example:"Aristotle saw virtue as the key to happiness." },
  { id: "b210", level:"C1", topic:"Nuanced",     word:"Paradoxically / Ostensibly / Inherently",translation:"פרדוקסלית / לכאורה / מטבע הדברים",example:"Ostensibly a comedy, the film is deeply tragic." },
  { id: "b211", level:"C1", topic:"Nuanced",     word:"Contentious / Tenuous / Unequivocal",translation:"שנוי במחלוקת / רופף / חד-משמעי",example:"The link between the two events is tenuous." },
  { id: "b212", level:"C1", topic:"Business",    word:"Leverage / Synergy / Disruptive",translation:"למנף / סינרגיה / משבש",example:"We need to leverage our existing partnerships." },
  { id: "b213", level:"C1", topic:"Business",    word:"Due diligence / Takeover / Merger",translation:"בדיקת נאותות / השתלטות / מיזוג",example:"They conducted thorough due diligence." },
  { id: "b214", level:"C1", topic:"Formal phrases",word:"I would venture to suggest / One might argue",translation:"אני מעז להציע / ניתן לטעון",example:"One might argue that the data is inconclusive." },
  { id: "b215", level:"C1", topic:"Formal phrases",word:"It is worth considering / It bears noting",translation:"כדאי לשקול / ראוי לציין",example:"It is worth considering the long-term implications." },
  { id: "b216", level:"C1", topic:"Society",     word:"Marginalised / Disenfranchised / Empower",translation:"מודר / מנועה מזכויות / להעצים",example:"The project empowers marginalised communities." },
  { id: "b217", level:"C1", topic:"Society",     word:"Cohesion / Fragmentation / Polarisation",translation:"לכידות / פרגמנטציה / פולריזציה",example:"Social polarisation threatens democracy." },
  { id: "b218", level:"C1", topic:"Collocations",word:"Cast doubt on / Lend credence to",translation:"להטיל ספק / לתת אמינות",example:"New evidence casts doubt on the original theory." },
  { id: "b219", level:"C1", topic:"Collocations",word:"Come to light / Bring to bear / Shed light on",translation:"להתגלות / להפעיל / לשפוך אור",example:"New facts have come to light." },

  // ── C2 – Mastery ──────────────────────────────────────────────────────────
  { id: "b250", level:"C2", topic:"Literary",    word:"Liminal / Laconic / Lapidary",translation:"על הסף / לאקוני / חקוק",example:"The story exists in a liminal space between dream and reality." },
  { id: "b251", level:"C2", topic:"Literary",    word:"Sibilance / Assonance / Onomatopoeia",translation:"שריקה / אסונאנס / אונומטופיאה",example:"The sibilance of the poem creates a whispering effect." },
  { id: "b252", level:"C2", topic:"Rhetoric",    word:"Aporia / Synecdoche / Periphrasis",translation:"אפוריה / סינקדוכה / פריפרזה",example:"Shakespeare uses synecdoche in 'All hands on deck'." },
  { id: "b253", level:"C2", topic:"Philosophy",  word:"Solipsism / Nihilism / Absurdism",translation:"סולפסיזם / ניהיליזם / אבסורדיזם",example:"Camus rejected both nihilism and absurdism." },
  { id: "b254", level:"C2", topic:"Language",    word:"Morpheme / Phoneme / Syntax",translation:"מורפמה / פונמה / תחביר",example:"The morpheme '-ing' turns a verb into a noun or adjective." },
  { id: "b255", level:"C2", topic:"Language",    word:"Deixis / Anaphora (ling.) / Elision",translation:"דיאיקסיס / אנפורה / השמטה",example:"The word 'here' is deictic – its meaning depends on context." },
  { id: "b256", level:"C2", topic:"High register",word:"Disquisition / Élan / Probity",translation:"מסה / מרץ / יושרה",example:"His probity was never in doubt throughout his career." },
  { id: "b257", level:"C2", topic:"High register",word:"Malfeasance / Sycophant / Obsequious",translation:"עוולה / חנפן / חנפני",example:"The obsequious aide agreed with everything the minister said." },
  { id: "b258", level:"C2", topic:"High register",word:"Pernicious / Invidious / Specious",translation:"מזיק / פוגעני / מרמה",example:"The report contained specious reasoning." },
  { id: "b259", level:"C2", topic:"Idioms",      word:"Throw a spanner in the works / Pull strings",translation:"לשבש תכניות / למשוך בחוטים",example:"The new law threw a spanner in the works." },
  { id: "b260", level:"C2", topic:"Idioms",      word:"Fly in the face of / Stand one's ground",translation:"לסתור / לעמוד על עמדתו",example:"His findings fly in the face of conventional wisdom." },
  { id: "b261", level:"C2", topic:"Collocations",word:"Defy categorisation / Defy expectations",translation:"לאתגר קטגוריות / לאתגר ציפיות",example:"Her work defies easy categorisation." },
  { id: "b262", level:"C2", topic:"Collocations",word:"Tacit understanding / Tacit approval",translation:"הבנה מובלעת / אישור לא מפורש",example:"There was a tacit understanding between them." },
  { id: "b263", level:"C2", topic:"Science",     word:"Stochastic / Heuristic / Deterministic",translation:"סטוכסטי / היוריסטי / דטרמיניסטי",example:"A heuristic approach finds good solutions quickly." },
  { id: "b264", level:"C2", topic:"Phrases",     word:"Ipso facto / De facto / A priori",translation:"מעצם העובדה / בפועל / מראש",example:"The de facto leader was not the elected one." },
  { id: "b265", level:"C2", topic:"Phrases",     word:"Non sequitur / Sui generis / Quid pro quo",translation:"חוסר קשר לוגי / ייחודי / גומלין",example:"That remark was a complete non sequitur." },
];

export function getBankByLevel(level: CEFRLevel | "all"): BankWord[] {
  if (level === "all") return VOCAB_BANK;
  return VOCAB_BANK.filter(w => w.level === level);
}

export function getBankTopics(level: CEFRLevel): string[] {
  const words = getBankByLevel(level);
  return [...new Set(words.map(w => w.topic))];
}
